version: '3.4'

networks: 
  frontend:
  backend:

services:
  catalog:
    image: Event/CatalogApi
    build: 
      context: ./EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      DatabaseServer:
      DatabaseName:
      DatbaseUser:
      DatabasePassaword: 
      ExternalCatalogBaseUrl: 

    ports: 
    
